[package]
name = "patch-svd"
version = "0.0.3"
authors = ["Alexander Huymayer"]
edition = "2018"
description = "Load and patch svd files. Pre-alpha version. No stable interface until version 0.1.0."
license = "MIT OR Apache-2.0"

[dependencies]
itertools = "0.9.*"
regex = "1.3.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_yaml = "0.8.*"
serde-xml-rs = "0.4.*"
